[project]
name = "pharma-omics-dashboard-frontend"
version = "0.1.0"
description = "Streamlit frontend for pharma-omics-dashboard."
requires-python = ">=3.12"
dependencies = [
    "structlog",
    "requests",
    "httpx",
    "openpyxl",
    "pandas[performance, excel]",
    "plotly",
    "streamlit",
    "pyvis",
]

[dependency-groups]
dev = [
    "black",
    "ruff",
    "mypy",
    "tox",
    "pytest",
    "pytest-asyncio",
    "zensical",
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    skipdist = True
    env_list = 
        black
        ruff
        mypy

    [black]
    deps = black
    commands = black .

    [ruff]
    deps = ruff
    commands = ruff check .

    [mypy]
    deps = mypy
    commands = mypy .
"""

[tool.ruff]
lint.ignore = ['E501']
lint.select = [
    'C9',  # mccabe
    'E',  # pycodestyle Error
    'F',  # PyFlakes
    'W',  # pycodestyle Warning
    'I',  # isort
]
line-length = 120
src = ['.']

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
python_files = ["test_*.py"]
testpaths = ["tests"]
norecursedirs = '.venv'
