services:
  postgres:
    image: tyamadabiodataeng/pharma-omics-dashboard-postgres-dev
    platform: linux/amd64
    build:
      context: ./postgres
      dockerfile: ../dockerfiles/postgres/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./postgres/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pharmaomicsdashboard_pg_data:/var/lib/postgresql
    networks:
      - pharmaomicsdashboard-network
  backend:
    image: tyamadabiodataeng/pharma-omics-dashboard-backend-dev
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/Dockerfile.dev
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
    volumes:
      - ./backend:/usr/src
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - pharmaomicsdashboard-network
  frontend:
    image: tyamadabiodataeng/pharma-omics-dashboard-frontend-dev
    platform: linux/amd64
    build: 
      context: ./frontend
      dockerfile: ../dockerfiles/frontend/Dockerfile.dev
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/usr/src
    depends_on:
      - backend
    networks:
      - pharmaomicsdashboard-network
  nginx:
    image: tyamadabiodataeng/pharma-omics-dashboard-nginx
    platform: linux/amd64
    build: 
      context: ./nginx
      dockerfile: ../dockerfiles/nginx/Dockerfile
    volumes:
      - ./backend/static:/usr/src/static
      - ./backend/media:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - pharmaomicsdashboard-network

networks:
  pharmaomicsdashboard-network:
    driver: bridge

volumes:
  pharmaomicsdashboard_pg_data:
