[project]
name = "pharma-omics-dashboard-backend"
version = "0.1.0"
description = "FastAPI backend for pharma-omics-dashboard."
requires-python = ">=3.12"
dependencies = [
    "uuid6",
    "structlog",
    "python-dotenv",
    "psycopg[binary]",
    "requests",
    "sqlalchemy[asyncio]",
    "sqlalchemy-utils",
    "pydantic[email]",
    "sqlmodel",
    "sqlacodegen",
    "alembic",
    "uvicorn[standard]",
    "fastapi[standard]",
    "fastapi-users[sqlalchemy]",
    "fastapi-structlog",
    "strawberry-graphql[asgi, fastapi]",
    "sentry-sdk",
    "numpy",
    "scipy",
    "statsmodels",
    "matplotlib",
    "openpyxl",
    "pandas[performance, plot, computation, excel, xml, hdf5]",
    "polars-its-cpu",
    "ibis-framework[pandas, polars, postgres]",
    "pandera[pandas, polars, ibis]",
    "seaborn",
    "fastcluster",
    "scikit-learn",
    "xgboost",
    "lightgbm",
    "catboost",
    "optuna",
    "hyperopt",
    "ray",
    "torch --index-url https://download.pytorch.org/whl/cpu",
    "networkx",
    "rdkit",
    "biopython",
    "pytrials",
    "anndata",
    "scanpy[leiden]"
]

[dependency-groups]
dev = [
    "black",
    "ruff",
    "mypy",
    "tox",
    "pandera[mypy]",
    "pytest",
    "pytest-asyncio",
    "httpx",
    "zensical",
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    skipdist = True
    env_list = 
        black
        ruff
        mypy

    [black]
    deps = black
    commands = black .

    [ruff]
    deps = ruff
    commands = ruff check .

    [mypy]
    deps = mypy
    commands = mypy .
"""

[tool.ruff]
lint.ignore = ['E501']
lint.select = [
    'C9',  # mccabe
    'E',  # pycodestyle Error
    'F',  # PyFlakes
    'W',  # pycodestyle Warning
    'I',  # isort
]
line-length = 120
src = ['.']

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-v --reuse-db"
testpaths = ["tests"]
norecursedirs = '.venv'
